name: BetterHarvest
version: ${project.version}
main: ideias.mano.betterHarvest.BetterHarvest
api-version: 1.15
load: STARTUP
authors: [MestreProno]
description: Right click crops to harvest and replant them
website: https://github.com/brunofauth

permissions:
  BetterHarvest.*:
    description: Grants you all the permissions used by this plugin
    default: false
    children:
      BetterHarvest.harvest.*: true
      BetterHarvest.replant.*: true
  BetterHarvest.harvest.*:
    default: false
    children:
      BetterHarvest.harvest.WHEAT: true
      BetterHarvest.harvest.CARROTS: true
      BetterHarvest.harvest.POTATOES: true
      BetterHarvest.harvest.BEETROOTS: true
      BetterHarvest.harvest.NETHER_WART: true
      BetterHarvest.harvest.COCOA: true
  BetterHarvest.harvest.WHEAT:
    description: Allows you to harvest wheat by right clicking on it
    default: false
  BetterHarvest.harvest.CARROTS:
    description: Allows you to harvest carrots by right clicking on them
    default: false
  BetterHarvest.harvest.POTATOES:
    description: Allows you to harvest potatoes by right clicking on them
    default: false
  BetterHarvest.harvest.BEETROOTS:
    description: Allows you to harvest beetroots by right clicking on them
    default: false
  BetterHarvest.harvest.NETHER_WART:
    description: Allows you to harvest nether wart by right clicking on it
    default: false
  BetterHarvest.harvest.COCOA:
    description: Allows you to harvest cocoa beans by right clicking on them
    default: false
  BetterHarvest.replant.*:
    default: false
    children:
      BetterHarvest.replant.WHEAT: true
      BetterHarvest.replant.CARROTS: true
      BetterHarvest.replant.POTATOES: true
      BetterHarvest.replant.BEETROOTS: true
      BetterHarvest.replant.NETHER_WART: true
      BetterHarvest.replant.COCOA: true
  BetterHarvest.replant.WHEAT:
    description: Allows you to replant wheat after right-click-harvesting it
    default: false
  BetterHarvest.replant.CARROTS:
    description: Allows you to replant carrots after right-click-harvesting them
    default: false
  BetterHarvest.replant.POTATOES:
    description: Allows you to replant potatoes after right-click-harvesting them
    default: false
  BetterHarvest.replant.BEETROOTS:
    description: Allows you to replant beetroots after right-click-harvesting them
    default: false
  BetterHarvest.replant.NETHER_WART:
    description: Allows you to replant nether wart after right-click-harvesting it
    default: false
  BetterHarvest.replant.COCOA:
    description: Allows you to replant cocoa beans after right-click-harvesting them
    default: false
